name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      # Step 3: Install JavaFX SDK
      - name: Install JavaFX SDK
        run: sudo apt-get install openjfx

      # Step 4: Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: mvn test -X  # Enable full debug logging

      # Step 6: Display Surefire Reports
      - name: Display Surefire Reports
        run: |
          ls -la target/surefire-reports
          cat target/surefire-reports/*.txt
